scripts/107_from_Carl.py
=> Add Carl's hello Script

scripts/15_from_Luis.py
=> Add Luis' hello script

scripts/XX_from_Nestor.py
=> Add Nestor's hello script

scripts/03_from_Carolina.py
Hello, 
Here you have my hello script
=> Add Carolina's hello script

scripts/27_from_PabloJC.py
=> add Pablo's hello script

scripts/63_from_Daniel.py
=> adding Daniel's script

scripts/05_Fernando.py, scripts/05_from_Fernando.py
=> Add my hello Fernando

scripts/10_from_Neal.py, scripts/99_from_neal.py
=> Add my hello

scripts/99_from_alex.py
=> adding hello script

scripts/05_from_Kumar.py
=> Add Kumar's hello script

scripts/42069_from_Matt.py
The rug really pulls the whole room together man.
=> Add Matt's hello script

scripts/15_from_miana.py
=> Add Miana's hello script

scripts/007_from_garrettS.py
=> Added From Garrett!

scripts/16_from_Dani.py
=> Add Dani's Hello Script

scripts/03_from_Andy.py
Pull request for Andy's Hello Script
=> Add Andy's hello script

scripts/07_from_Brian.py
=> Add Brian's hello script

scripts/08_from_Regis.py
This is to add Regis's Hello Script to the github Collaboration repo
=> Add Regis's Hello script

scripts/16_from_Cristian.py, scripts/16_from_FirstName.py
Had two files mistake on the first try.
=> Cristian's add my hello

scripts/12_from_Chris.py, scripts/19_from_Michael.py
Please add descriptions to your PRs!
=> Fix script syntax

scripts/05_from_Chris.py
=> Add Chris's hello script

scripts/06_from_JoshuaBandong.py
=> Add Joshua Bandong's hello script

scripts/09_from_Jun.py
=> Add jj's hello script

scripts/01_from_Pete.py
=> Add Pete's first hello script

scripts/04_from_George.py
=> Add George's hello script
